__testfixtures__/ember-qunit-codemod/module-for-component.input.js, __testfixtures__/ember-qunit-codemod/module-for-component.output.js, ember-qunit-codemod.js
=> Add support for `this.clearRender()` -> `await clearRender()`

__testfixtures__/ember-qunit-codemod/module-for-component.input.js, __testfixtures__/ember-qunit-codemod/module-for-component.output.js, ember-qunit-codemod.js
=> Migrate `this._element` to `this.element`.

__testfixtures__/ember-qunit-codemod/register.input.js, __testfixtures__/ember-qunit-codemod/register.output.js, ember-qunit-codemod.js
Rewrite `this.registry.register` usage to `this.owner.register`
Rewrite `this.register` usage to `this.owner.register`
=> Replace `this.register` with `this.owner.register`

ember-qunit-codemod.js
as discussed on Slack yesterday
=> Move functions into main exported function to remove "j" parameters

__testfixtures__/ember-qunit-codemod/subject.input.js, __testfixtures__/ember-qunit-codemod/subject.output.js, ember-qunit-codemod.js
=> Implement this.subject transformation

__testfixtures__/ember-qunit-codemod/module-for-component.input.js, __testfixtures__/ember-qunit-codemod/module-for-component.output.js, ember-qunit-codemod.js
Fixes https://github.com/rwjblue/ember-qunit-codemod/issues/16
=> Support `this.render` in `beforeEach`.

__testfixtures__/ember-qunit-codemod/subject.input.js, __testfixtures__/ember-qunit-codemod/subject.output.js, ember-qunit-codemod.js
=> Ensure `this.subject` is processed in beforeEach.

__testfixtures__/ember-qunit-codemod/subject.input.js, __testfixtures__/ember-qunit-codemod/subject.output.js, ember-qunit-codemod.js
* Ensure `moduleFor('service:foo', { integration: true })` can detect subject
* Ensure `moduleFor('service:foo')` can detect subject
Fixes #15
=> Fix various issues with `subject` detection.

__testfixtures__/ember-qunit-codemod/get-owner-this.input.js, __testfixtures__/ember-qunit-codemod/get-owner-this.output.js, ember-qunit-codemod.js
=> Ensure `getOwner(this)` usage is rewritten.

__testfixtures__/ember-qunit-codemod/module-for-component.output.js, ember-qunit-codemod.js
=> Update to import `render` from `ember-test-helpers`.

__testfixtures__/ember-qunit-codemod/wait.input.js, __testfixtures__/ember-qunit-codemod/wait.output.js, ember-qunit-codemod.js
=> Update `wait` imports to `settled`.

__testfixtures__/ember-qunit-codemod/inject.input.js, __testfixtures__/ember-qunit-codemod/inject.output.js, ember-qunit-codemod.js
=> Handle dasherized service names.

__testfixtures__/ember-qunit-codemod/custom-functions-in-options.input.js, __testfixtures__/ember-qunit-codemod/custom-functions-in-options.output.js, ember-qunit-codemod.js
=> Ensure all options to moduleFor* are handled.

__testfixtures__/ember-qunit-codemod/native-qunit-to-nested.input.js, __testfixtures__/ember-qunit-codemod/native-qunit-to-nested.output.js, ember-qunit-codemod.js
=> Migrate "flat" QUnit usage to nested modules.

__testfixtures__/ember-qunit-codemod/remove-empty-import.input.js, __testfixtures__/ember-qunit-codemod/remove-empty-import.output.js, ember-qunit-codemod.js
Closes https://github.com/rwjblue/ember-qunit-codemod/issues/36
Let me know if this is what you were looking for... First time touching jscodeshift/recast/etc and the documentation is lacking...
=> Empty import bugfix

__testfixtures__/ember-qunit-codemod/subject.output.js, ember-qunit-codemod.js
=> Wrap `.createRecord` calls in `Ember.run.`

__testfixtures__/ember-qunit-codemod/on.input.js, __testfixtures__/ember-qunit-codemod/on.output.js, ember-qunit-codemod.js
Fixes https://github.com/rwjblue/ember-qunit-codemod/issues/45
=> Process `this.on` statements.

__testfixtures__/ember-qunit-codemod/resolver.input.js, __testfixtures__/ember-qunit-codemod/resolver.output.js, ember-qunit-codemod.js
=> Properly handle custom `resolver` option.

README.md, __testfixtures__/ember-qunit-codemod/global-wait.output.js, __testfixtures__/ember-qunit-codemod/module-for-acceptance.input.js, __testfixtures__/ember-qunit-codemod/module-for-acceptance.output.js, ember-qunit-codemod.js
@rwjblue Added a simple codemod for `setupApplicationTest` as well as a note to the readme that users should also use `ember-test-helpers-codemod`.
=> moduleForAcceptance codemod

.travis.yml, __testfixtures__/ember-qunit-codemod/nested-module-with-arrow.input.js, __testfixtures__/ember-qunit-codemod/nested-module-with-arrow.output.js, ember-qunit-codemod.js
Fixes https://github.com/rwjblue/ember-qunit-codemod/issues/83
=> Ensure existing nested modules using arrows are unchanged.

__testfixtures__/ember-qunit-codemod/module-for-acceptance.input.js, __testfixtures__/ember-qunit-codemod/module-for-acceptance.output.js, ember-qunit-codemod.js
Fixes https://github.com/rwjblue/ember-qunit-codemod/issues/90
=> Fix issue with pre-existing nested modules.

transforms/convert-module-for-to-setup-test/__testfixtures__/module-for-acceptance.input.js, transforms/convert-module-for-to-setup-test/__testfixtures__/module-for-acceptance.output.js, transforms/convert-module-for-to-setup-test/index.js
tester thing here: https://astexplorer.net/#/gist/b2fca05d880f0763f130414751157e1a/a7bb89000e37930dd5f1ba6a2dc73d452137613f
(for my own notes)
=> Fix inline andThen transforms

transforms/convert-module-for-to-setup-test/__testfixtures__/module-with-comments.input.js, transforms/convert-module-for-to-setup-test/__testfixtures__/module-with-comments.output.js, transforms/convert-module-for-to-setup-test/index.js
Related: https://github.com/ember-codemods/ember-qunit-codemod/issues/198
=> Fix Comments being lost around modules
